export interface ProtectedQualifierClaims {
  organic: boolean;
  glutenFree: boolean;
  nonGmo: boolean;
  plantBased: boolean;
  grassFed: boolean;
  grainFed: boolean;
  pastureRaised: boolean;
  freeRange: boolean;
  vegetarianFed: boolean;
  airChilled: boolean;
  wildCaught: boolean;
  farmRaised: boolean;
  boneState: "bone in" | "boneless" | null;
  skinState: "skin on" | "skinless" | null;
  frozenState: "never frozen" | "previously frozen" | "frozen" | null;
  leanPercent: string | null;
  grade: "prime" | "choice" | "select" | null;
  angus: boolean;
  wagyu: boolean;
  heritage: boolean;
  noAntibiotics: boolean;
  humane: boolean;
  halal: boolean;
  kosher: boolean;
  natural: boolean;
  ribMeat: boolean;
  valuePack: boolean;
  bulk: boolean;
  waterState: "no water added" | "water added" | null;
  smoked: boolean;
  marinated: boolean;
  seasoned: boolean;
  uncured: boolean;
}

export function protectedQualifierClaims(value: unknown): ProtectedQualifierClaims;
export function productQualifiersCompatible(left: unknown, right: unknown): boolean;
export function crossSourceQualifiersCompatible(left: unknown, right: unknown): boolean;
export function productQualifierEvidence(record: unknown): string;
export function numericProductVariantsCompatible(left: unknown, right: unknown): boolean;
